source("R/ingest.R")
source("R/validate.R")
source("R/clean.R")
source("R/derive.R")
source("R/report1.R")
source("R/report2.R")
source("R/report3.R")
source("R/summary.R")

library(testthat)

fixture_path <- "sample-data/tiny_fixture.csv"

test_that("tiny fixture end-to-end pipeline", {
  raw <- ingest_csv(fixture_path)
  validate_schema(raw)
  cleaned <- clean_data(raw)
  derived <- derive_fields(cleaned)
  filtered <- filter_years(derived)
  assert_year_filter(filtered)
  expect_true(all(filtered$FundingYear %in% 2021:2023))
  expect_equal(nrow(filtered), 11)
  cebu_rows <- subset(filtered, Province == "Cebu" & FundingYear == 2021)
  expect_true(all(!is.na(cebu_rows$Latitude)))
  albay_na <- subset(filtered, Province == "Albay" & FundingYear == 2022 & Contractor == "Delta Works")
  expect_true(all(!is.na(albay_na$Latitude)))
  report1 <- report_regional_efficiency(filtered)
  expect_true(all(report1$EfficiencyScore <= 100 | is.na(report1$EfficiencyScore)))
  report2 <- report_top_contractors(filtered)
  expect_true(all(report2$NProjects >= 5))
  report3 <- report_overrun_trends(filtered)
  expect_true(all(report3$FundingYear %in% 2021:2023))
  summary <- build_summary(filtered)
  expect_equal(summary$total_projects, nrow(filtered))
})
